<?php

/**
 * BaseCollection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $StorageLocations
 * @property Doctrine_Collection $CollectionStorageLocation
 * 
 * @method Doctrine_Collection getStorageLocations()          Returns the current record's "StorageLocations" collection
 * @method Doctrine_Collection getCollectionStorageLocation() Returns the current record's "CollectionStorageLocation" collection
 * @method Collection          setStorageLocations()          Sets the current record's "StorageLocations" collection
 * @method Collection          setCollectionStorageLocation() Sets the current record's "CollectionStorageLocation" collection
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCollection extends SubUnit
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StorageLocation as StorageLocations', array(
             'refClass' => 'CollectionStorageLocation',
             'local' => 'collection_id',
             'foreign' => 'storage_location_id'));

        $this->hasMany('CollectionStorageLocation', array(
             'local' => 'id',
             'foreign' => 'collection_id'));
    }
}