<?php

/**
 * BaseStore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $inst_id
 * @property text $notes
 * @property integer $creator_id
 * @property integer $last_editor_id
 * @property string $type
 * @property text $resident_structure_description
 * @property integer $storage_location_id
 * @property integer $unit_personnel
 * @property integer $parent_node_id
 * @property string $status
 * @property string $location
 * @property integer $format_id
 * @property User $Creator
 * @property User $Editor
 * @property Doctrine_Collection $EvaluatorActions
 * 
 * @method string              getName()                           Returns the current record's "name" value
 * @method string              getInstId()                         Returns the current record's "inst_id" value
 * @method text                getNotes()                          Returns the current record's "notes" value
 * @method integer             getCreatorId()                      Returns the current record's "creator_id" value
 * @method integer             getLastEditorId()                   Returns the current record's "last_editor_id" value
 * @method string              getType()                           Returns the current record's "type" value
 * @method text                getResidentStructureDescription()   Returns the current record's "resident_structure_description" value
 * @method integer             getStorageLocationId()              Returns the current record's "storage_location_id" value
 * @method integer             getUnitPersonnel()                  Returns the current record's "unit_personnel" value
 * @method integer             getParentNodeId()                   Returns the current record's "parent_node_id" value
 * @method string              getStatus()                         Returns the current record's "status" value
 * @method string              getLocation()                       Returns the current record's "location" value
 * @method integer             getFormatId()                       Returns the current record's "format_id" value
 * @method User                getCreator()                        Returns the current record's "Creator" value
 * @method User                getEditor()                         Returns the current record's "Editor" value
 * @method Doctrine_Collection getEvaluatorActions()               Returns the current record's "EvaluatorActions" collection
 * @method Store               setName()                           Sets the current record's "name" value
 * @method Store               setInstId()                         Sets the current record's "inst_id" value
 * @method Store               setNotes()                          Sets the current record's "notes" value
 * @method Store               setCreatorId()                      Sets the current record's "creator_id" value
 * @method Store               setLastEditorId()                   Sets the current record's "last_editor_id" value
 * @method Store               setType()                           Sets the current record's "type" value
 * @method Store               setResidentStructureDescription()   Sets the current record's "resident_structure_description" value
 * @method Store               setStorageLocationId()              Sets the current record's "storage_location_id" value
 * @method Store               setUnitPersonnel()                  Sets the current record's "unit_personnel" value
 * @method Store               setParentNodeId()                   Sets the current record's "parent_node_id" value
 * @method Store               setStatus()                         Sets the current record's "status" value
 * @method Store               setLocation()                       Sets the current record's "location" value
 * @method Store               setFormatId()                       Sets the current record's "format_id" value
 * @method Store               setCreator()                        Sets the current record's "Creator" value
 * @method Store               setEditor()                         Sets the current record's "Editor" value
 * @method Store               setEvaluatorActions()               Sets the current record's "EvaluatorActions" collection
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('store');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('inst_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('notes', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('creator_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('last_editor_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('resident_structure_description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('storage_location_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('unit_personnel', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parent_node_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('format_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->setSubClasses(array(
             'Unit' => 
             array(
              'type' => 1,
             ),
             'SubUnit' => 
             array(
              'type' => 2,
             ),
             'Collection' => 
             array(
              'type' => 3,
             ),
             'AssetGroup' => 
             array(
              'type' => 4,
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as Creator', array(
             'local' => 'creator_id',
             'foreign' => 'id'));

        $this->hasOne('User as Editor', array(
             'local' => 'last_editor_id',
             'foreign' => 'id'));

        $this->hasMany('EvaluatorHistory as EvaluatorActions', array(
             'local' => 'id',
             'foreign' => 'asset_group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}