<?php

/**
 * BaseCharacteristicsValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $c_name
 * @property float $c_score
 * @property integer $format_id
 * @property integer $constraint_id
 * @property integer $parent_characteristic_id
 * @property CharacteristicsFormat $CharacteristicsFormat
 * @property FormatType $FormatType
 * @property CharacteristicsConstraints $CharacteristicsConstraints
 * 
 * @method string                     getCName()                      Returns the current record's "c_name" value
 * @method float                      getCScore()                     Returns the current record's "c_score" value
 * @method integer                    getFormatId()                   Returns the current record's "format_id" value
 * @method integer                    getConstraintId()               Returns the current record's "constraint_id" value
 * @method integer                    getParentCharacteristicId()     Returns the current record's "parent_characteristic_id" value
 * @method CharacteristicsFormat      getCharacteristicsFormat()      Returns the current record's "CharacteristicsFormat" value
 * @method FormatType                 getFormatType()                 Returns the current record's "FormatType" value
 * @method CharacteristicsConstraints getCharacteristicsConstraints() Returns the current record's "CharacteristicsConstraints" value
 * @method CharacteristicsValues      setCName()                      Sets the current record's "c_name" value
 * @method CharacteristicsValues      setCScore()                     Sets the current record's "c_score" value
 * @method CharacteristicsValues      setFormatId()                   Sets the current record's "format_id" value
 * @method CharacteristicsValues      setConstraintId()               Sets the current record's "constraint_id" value
 * @method CharacteristicsValues      setParentCharacteristicId()     Sets the current record's "parent_characteristic_id" value
 * @method CharacteristicsValues      setCharacteristicsFormat()      Sets the current record's "CharacteristicsFormat" value
 * @method CharacteristicsValues      setFormatType()                 Sets the current record's "FormatType" value
 * @method CharacteristicsValues      setCharacteristicsConstraints() Sets the current record's "CharacteristicsConstraints" value
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCharacteristicsValues extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('characteristics_values');
        $this->hasColumn('c_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('c_score', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('format_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('constraint_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('parent_characteristic_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CharacteristicsFormat', array(
             'local' => 'parent_characteristic_id',
             'foreign' => 'id'));

        $this->hasOne('FormatType', array(
             'local' => 'format_id',
             'foreign' => 'id'));

        $this->hasOne('CharacteristicsConstraints', array(
             'local' => 'constraint_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}