<?php

/**
 * BaseUnitPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $unit_id
 * @property integer $person_id
 * @property Unit $Unit
 * @property Person $Person
 * 
 * @method integer    getUnitId()    Returns the current record's "unit_id" value
 * @method integer    getPersonId()  Returns the current record's "person_id" value
 * @method Unit       getUnit()      Returns the current record's "Unit" value
 * @method Person     getPerson()    Returns the current record's "Person" value
 * @method UnitPerson setUnitId()    Sets the current record's "unit_id" value
 * @method UnitPerson setPersonId()  Sets the current record's "person_id" value
 * @method UnitPerson setUnit()      Sets the current record's "Unit" value
 * @method UnitPerson setPerson()    Sets the current record's "Person" value
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnitPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unit_person');
        $this->hasColumn('unit_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Unit', array(
             'local' => 'unit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}