<?php

/**
 * BaseSubUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Unit
 * 
 * @method Doctrine_Collection getUnit() Returns the current record's "Unit" collection
 * @method SubUnit             setUnit() Sets the current record's "Unit" collection
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubUnit extends Store
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Unit', array(
             'local' => 'parent_node_id',
             'foreign' => 'id'));
    }
}