<?php

/**
 * BaseEvaluatorHistoryPersonnel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $evaluator_history_id
 * @property integer $person_id
 * 
 * @method integer                   getEvaluatorHistoryId()   Returns the current record's "evaluator_history_id" value
 * @method integer                   getPersonId()             Returns the current record's "person_id" value
 * @method EvaluatorHistoryPersonnel setEvaluatorHistoryId()   Sets the current record's "evaluator_history_id" value
 * @method EvaluatorHistoryPersonnel setPersonId()             Sets the current record's "person_id" value
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvaluatorHistoryPersonnel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evaluator_history_personnel');
        $this->hasColumn('evaluator_history_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}