<?php

/**
 * BaseEvaluator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvaluator extends User
{
    public function setUp()
    {
        parent::setUp();
        
    }
}