<?php

/**
 * BasePressed45RPMDisc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePressed45RPMDisc extends PressedAudioDiscFormatType
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('pressed45_r_p_m_disc');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}