<?php

/**
 * BaseEvaluator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $HistoryInstances
 * 
 * @method Doctrine_Collection getHistoryInstances() Returns the current record's "HistoryInstances" collection
 * @method Evaluator           setHistoryInstances() Sets the current record's "HistoryInstances" collection
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvaluator extends User
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EvaluatorHistory as HistoryInstances', array(
             'local' => 'id',
             'foreign' => 'evaluator_id'));
    }
}