<?php

/**
 * Base8MM
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $recordingSpeed
 * @property boolean $binderSystem
 * 
 * @method integer getRecordingSpeed() Returns the current record's "recordingSpeed" value
 * @method boolean getBinderSystem()   Returns the current record's "binderSystem" value
 * @method 8MM     setRecordingSpeed() Sets the current record's "recordingSpeed" value
 * @method 8MM     setBinderSystem()   Sets the current record's "binderSystem" value
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base8MM extends ReelVideoRecordingFormatType
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('8_m_m');
        $this->hasColumn('recordingSpeed', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('binderSystem', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}