<?php

// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pressed45RPMDisc', 'doctrine');

/**
 * BasePressed45RPMDisc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $quantity
 * @property integer $generation
 * @property string $year_recorded
 * @property integer $copies
 * @property string $stock_brand
 * @property integer $off_brand
 * @property integer $fungus
 * @property integer $other_contaminants
 * @property string $duration
 * @property string $duration_type
 * @property string $duration_type_methodology
 * @property string $format_notes
 * @property string $type
 * @property integer $material
 * @property integer $oxidationcorrosion
 * @property integer $pack_deformation
 * @property integer $noise_reduction
 * @property integer $tape_type
 * @property integer $thin_tape
 * @property integer $slow_speed
 * @property integer $sound_field
 * @property integer $soft_binder_syndrome
 * @property integer $gauge
 * @property integer $color
 * @property integer $colorfade
 * @property integer $soundtrackformat
 * @property integer $substrate
 * @property integer $strongodor
 * @property integer $vinegarodor
 * @property integer $adstriplevel
 * @property integer $shrinkage
 * @property integer $levelofshrinkage
 * @property integer $rust
 * @property integer $discoloration
 * @property integer $surfaceblisteringbubbling
 * @property integer $thintape
 * @property integer $1993orearlier
 * @property integer $datagradetape
 * @property integer $longplay32k96k
 * @property integer $corrosionrustoxidation
 * @property integer $composition
 * @property integer $nonstandardbrand
 * @property integer $trackconfiguration
 * @property integer $tapethickness
 * @property string $speed
 * @property integer $softbindersyndrome
 * @property integer $materialsbreakdown
 * @property integer $physicaldamage
 * @property integer $delamination
 * @property integer $plasticizerexudation
 * @property integer $recordinglayer
 * @property integer $recordingspeed
 * @property integer $cylindertype
 * @property string $reflectivelayer
 * @property string $datalayer
 * @property integer $opticaldisctype
 * @property integer $format
 * @property integer $recordingstandard
 * @property date $publicationyear
 * @property integer $capacitylayers
 * @property string $codec
 * @property string $datarate
 * @property integer $sheddingsoftbinder
 * @property integer $formatversion
 * @property integer $oxide
 * @property integer $bindersystem
 * @property string $reelsize
 * @property integer $whiteresidue
 * @property integer $size
 * @property integer $formattypedvideorecordingformat
 * @property string $bitrate
 * @property integer $scanning
 * @property integer $format_id
 * @property string $f_c_name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer          getId()                              Returns the current record's "id" value
 * @method integer          getQuantity()                        Returns the current record's "quantity" value
 * @method integer          getGeneration()                      Returns the current record's "generation" value
 * @method string           getYearRecorded()                    Returns the current record's "year_recorded" value
 * @method integer          getCopies()                          Returns the current record's "copies" value
 * @method string           getStockBrand()                      Returns the current record's "stock_brand" value
 * @method integer          getOffBrand()                        Returns the current record's "off_brand" value
 * @method integer          getFungus()                          Returns the current record's "fungus" value
 * @method integer          getOtherContaminants()               Returns the current record's "other_contaminants" value
 * @method string           getDuration()                        Returns the current record's "duration" value
 * @method string           getDurationType()                    Returns the current record's "duration_type" value
 * @method string           getDurationTypeMethodology()         Returns the current record's "duration_type_methodology" value
 * @method string           getFormatNotes()                     Returns the current record's "format_notes" value
 * @method string           getType()                            Returns the current record's "type" value
 * @method integer          getMaterial()                        Returns the current record's "material" value
 * @method integer          getOxidationcorrosion()              Returns the current record's "oxidationcorrosion" value
 * @method integer          getPackDeformation()                 Returns the current record's "pack_deformation" value
 * @method integer          getNoiseReduction()                  Returns the current record's "noise_reduction" value
 * @method integer          getTapeType()                        Returns the current record's "tape_type" value
 * @method integer          getThinTape()                        Returns the current record's "thin_tape" value
 * @method integer          getSlowSpeed()                       Returns the current record's "slow_speed" value
 * @method integer          getSoundField()                      Returns the current record's "sound_field" value
 * @method integer          getSoftBinderSyndrome()              Returns the current record's "soft_binder_syndrome" value
 * @method integer          getGauge()                           Returns the current record's "gauge" value
 * @method integer          getColor()                           Returns the current record's "color" value
 * @method integer          getColorfade()                       Returns the current record's "colorfade" value
 * @method integer          getSoundtrackformat()                Returns the current record's "soundtrackformat" value
 * @method integer          getSubstrate()                       Returns the current record's "substrate" value
 * @method integer          getStrongodor()                      Returns the current record's "strongodor" value
 * @method integer          getVinegarodor()                     Returns the current record's "vinegarodor" value
 * @method integer          getAdstriplevel()                    Returns the current record's "adstriplevel" value
 * @method integer          getShrinkage()                       Returns the current record's "shrinkage" value
 * @method integer          getLevelofshrinkage()                Returns the current record's "levelofshrinkage" value
 * @method integer          getRust()                            Returns the current record's "rust" value
 * @method integer          getDiscoloration()                   Returns the current record's "discoloration" value
 * @method integer          getSurfaceblisteringbubbling()       Returns the current record's "surfaceblisteringbubbling" value
 * @method integer          getThintape()                        Returns the current record's "thintape" value
 * @method integer          get1993orearlier()                   Returns the current record's "1993orearlier" value
 * @method integer          getDatagradetape()                   Returns the current record's "datagradetape" value
 * @method integer          getLongplay32k96k()                  Returns the current record's "longplay32k96k" value
 * @method integer          getCorrosionrustoxidation()          Returns the current record's "corrosionrustoxidation" value
 * @method integer          getComposition()                     Returns the current record's "composition" value
 * @method integer          getNonstandardbrand()                Returns the current record's "nonstandardbrand" value
 * @method integer          getTrackconfiguration()              Returns the current record's "trackconfiguration" value
 * @method integer          getTapethickness()                   Returns the current record's "tapethickness" value
 * @method string           getSpeed()                           Returns the current record's "speed" value
 * @method integer          getSoftbindersyndrome()              Returns the current record's "softbindersyndrome" value
 * @method integer          getMaterialsbreakdown()              Returns the current record's "materialsbreakdown" value
 * @method integer          getPhysicaldamage()                  Returns the current record's "physicaldamage" value
 * @method integer          getDelamination()                    Returns the current record's "delamination" value
 * @method integer          getPlasticizerexudation()            Returns the current record's "plasticizerexudation" value
 * @method integer          getRecordinglayer()                  Returns the current record's "recordinglayer" value
 * @method integer          getRecordingspeed()                  Returns the current record's "recordingspeed" value
 * @method integer          getCylindertype()                    Returns the current record's "cylindertype" value
 * @method string           getReflectivelayer()                 Returns the current record's "reflectivelayer" value
 * @method string           getDatalayer()                       Returns the current record's "datalayer" value
 * @method integer          getOpticaldisctype()                 Returns the current record's "opticaldisctype" value
 * @method integer          getFormat()                          Returns the current record's "format" value
 * @method integer          getRecordingstandard()               Returns the current record's "recordingstandard" value
 * @method date             getPublicationyear()                 Returns the current record's "publicationyear" value
 * @method integer          getCapacitylayers()                  Returns the current record's "capacitylayers" value
 * @method string           getCodec()                           Returns the current record's "codec" value
 * @method string           getDatarate()                        Returns the current record's "datarate" value
 * @method integer          getSheddingsoftbinder()              Returns the current record's "sheddingsoftbinder" value
 * @method integer          getFormatversion()                   Returns the current record's "formatversion" value
 * @method integer          getOxide()                           Returns the current record's "oxide" value
 * @method integer          getBindersystem()                    Returns the current record's "bindersystem" value
 * @method string           getReelsize()                        Returns the current record's "reelsize" value
 * @method integer          getWhiteresidue()                    Returns the current record's "whiteresidue" value
 * @method integer          getSize()                            Returns the current record's "size" value
 * @method integer          getFormattypedvideorecordingformat() Returns the current record's "formattypedvideorecordingformat" value
 * @method string           getBitrate()                         Returns the current record's "bitrate" value
 * @method integer          getScanning()                        Returns the current record's "scanning" value
 * @method integer          getFormatId()                        Returns the current record's "format_id" value
 * @method string           getFCName()                          Returns the current record's "f_c_name" value
 * @method timestamp        getCreatedAt()                       Returns the current record's "created_at" value
 * @method timestamp        getUpdatedAt()                       Returns the current record's "updated_at" value
 * @method Pressed45RPMDisc setId()                              Sets the current record's "id" value
 * @method Pressed45RPMDisc setQuantity()                        Sets the current record's "quantity" value
 * @method Pressed45RPMDisc setGeneration()                      Sets the current record's "generation" value
 * @method Pressed45RPMDisc setYearRecorded()                    Sets the current record's "year_recorded" value
 * @method Pressed45RPMDisc setCopies()                          Sets the current record's "copies" value
 * @method Pressed45RPMDisc setStockBrand()                      Sets the current record's "stock_brand" value
 * @method Pressed45RPMDisc setOffBrand()                        Sets the current record's "off_brand" value
 * @method Pressed45RPMDisc setFungus()                          Sets the current record's "fungus" value
 * @method Pressed45RPMDisc setOtherContaminants()               Sets the current record's "other_contaminants" value
 * @method Pressed45RPMDisc setDuration()                        Sets the current record's "duration" value
 * @method Pressed45RPMDisc setDurationType()                    Sets the current record's "duration_type" value
 * @method Pressed45RPMDisc setDurationTypeMethodology()         Sets the current record's "duration_type_methodology" value
 * @method Pressed45RPMDisc setFormatNotes()                     Sets the current record's "format_notes" value
 * @method Pressed45RPMDisc setType()                            Sets the current record's "type" value
 * @method Pressed45RPMDisc setMaterial()                        Sets the current record's "material" value
 * @method Pressed45RPMDisc setOxidationcorrosion()              Sets the current record's "oxidationcorrosion" value
 * @method Pressed45RPMDisc setPackDeformation()                 Sets the current record's "pack_deformation" value
 * @method Pressed45RPMDisc setNoiseReduction()                  Sets the current record's "noise_reduction" value
 * @method Pressed45RPMDisc setTapeType()                        Sets the current record's "tape_type" value
 * @method Pressed45RPMDisc setThinTape()                        Sets the current record's "thin_tape" value
 * @method Pressed45RPMDisc setSlowSpeed()                       Sets the current record's "slow_speed" value
 * @method Pressed45RPMDisc setSoundField()                      Sets the current record's "sound_field" value
 * @method Pressed45RPMDisc setSoftBinderSyndrome()              Sets the current record's "soft_binder_syndrome" value
 * @method Pressed45RPMDisc setGauge()                           Sets the current record's "gauge" value
 * @method Pressed45RPMDisc setColor()                           Sets the current record's "color" value
 * @method Pressed45RPMDisc setColorfade()                       Sets the current record's "colorfade" value
 * @method Pressed45RPMDisc setSoundtrackformat()                Sets the current record's "soundtrackformat" value
 * @method Pressed45RPMDisc setSubstrate()                       Sets the current record's "substrate" value
 * @method Pressed45RPMDisc setStrongodor()                      Sets the current record's "strongodor" value
 * @method Pressed45RPMDisc setVinegarodor()                     Sets the current record's "vinegarodor" value
 * @method Pressed45RPMDisc setAdstriplevel()                    Sets the current record's "adstriplevel" value
 * @method Pressed45RPMDisc setShrinkage()                       Sets the current record's "shrinkage" value
 * @method Pressed45RPMDisc setLevelofshrinkage()                Sets the current record's "levelofshrinkage" value
 * @method Pressed45RPMDisc setRust()                            Sets the current record's "rust" value
 * @method Pressed45RPMDisc setDiscoloration()                   Sets the current record's "discoloration" value
 * @method Pressed45RPMDisc setSurfaceblisteringbubbling()       Sets the current record's "surfaceblisteringbubbling" value
 * @method Pressed45RPMDisc setThintape()                        Sets the current record's "thintape" value
 * @method Pressed45RPMDisc set1993orearlier()                   Sets the current record's "1993orearlier" value
 * @method Pressed45RPMDisc setDatagradetape()                   Sets the current record's "datagradetape" value
 * @method Pressed45RPMDisc setLongplay32k96k()                  Sets the current record's "longplay32k96k" value
 * @method Pressed45RPMDisc setCorrosionrustoxidation()          Sets the current record's "corrosionrustoxidation" value
 * @method Pressed45RPMDisc setComposition()                     Sets the current record's "composition" value
 * @method Pressed45RPMDisc setNonstandardbrand()                Sets the current record's "nonstandardbrand" value
 * @method Pressed45RPMDisc setTrackconfiguration()              Sets the current record's "trackconfiguration" value
 * @method Pressed45RPMDisc setTapethickness()                   Sets the current record's "tapethickness" value
 * @method Pressed45RPMDisc setSpeed()                           Sets the current record's "speed" value
 * @method Pressed45RPMDisc setSoftbindersyndrome()              Sets the current record's "softbindersyndrome" value
 * @method Pressed45RPMDisc setMaterialsbreakdown()              Sets the current record's "materialsbreakdown" value
 * @method Pressed45RPMDisc setPhysicaldamage()                  Sets the current record's "physicaldamage" value
 * @method Pressed45RPMDisc setDelamination()                    Sets the current record's "delamination" value
 * @method Pressed45RPMDisc setPlasticizerexudation()            Sets the current record's "plasticizerexudation" value
 * @method Pressed45RPMDisc setRecordinglayer()                  Sets the current record's "recordinglayer" value
 * @method Pressed45RPMDisc setRecordingspeed()                  Sets the current record's "recordingspeed" value
 * @method Pressed45RPMDisc setCylindertype()                    Sets the current record's "cylindertype" value
 * @method Pressed45RPMDisc setReflectivelayer()                 Sets the current record's "reflectivelayer" value
 * @method Pressed45RPMDisc setDatalayer()                       Sets the current record's "datalayer" value
 * @method Pressed45RPMDisc setOpticaldisctype()                 Sets the current record's "opticaldisctype" value
 * @method Pressed45RPMDisc setFormat()                          Sets the current record's "format" value
 * @method Pressed45RPMDisc setRecordingstandard()               Sets the current record's "recordingstandard" value
 * @method Pressed45RPMDisc setPublicationyear()                 Sets the current record's "publicationyear" value
 * @method Pressed45RPMDisc setCapacitylayers()                  Sets the current record's "capacitylayers" value
 * @method Pressed45RPMDisc setCodec()                           Sets the current record's "codec" value
 * @method Pressed45RPMDisc setDatarate()                        Sets the current record's "datarate" value
 * @method Pressed45RPMDisc setSheddingsoftbinder()              Sets the current record's "sheddingsoftbinder" value
 * @method Pressed45RPMDisc setFormatversion()                   Sets the current record's "formatversion" value
 * @method Pressed45RPMDisc setOxide()                           Sets the current record's "oxide" value
 * @method Pressed45RPMDisc setBindersystem()                    Sets the current record's "bindersystem" value
 * @method Pressed45RPMDisc setReelsize()                        Sets the current record's "reelsize" value
 * @method Pressed45RPMDisc setWhiteresidue()                    Sets the current record's "whiteresidue" value
 * @method Pressed45RPMDisc setSize()                            Sets the current record's "size" value
 * @method Pressed45RPMDisc setFormattypedvideorecordingformat() Sets the current record's "formattypedvideorecordingformat" value
 * @method Pressed45RPMDisc setBitrate()                         Sets the current record's "bitrate" value
 * @method Pressed45RPMDisc setScanning()                        Sets the current record's "scanning" value
 * @method Pressed45RPMDisc setFormatId()                        Sets the current record's "format_id" value
 * @method Pressed45RPMDisc setFCName()                          Sets the current record's "f_c_name" value
 * @method Pressed45RPMDisc setCreatedAt()                       Sets the current record's "created_at" value
 * @method Pressed45RPMDisc setUpdatedAt()                       Sets the current record's "updated_at" value
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePressed45RPMDisc extends sfDoctrineRecord {

    public function setTableDefinition() {
        $this->setTableName('pressed45_r_p_m_disc');
        $this->hasColumn('id', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => true,
            'autoincrement' => true,
            'length' => 8,
        ));
        $this->hasColumn('quantity', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('generation', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('year_recorded', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('copies', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('stock_brand', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('off_brand', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('fungus', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('other_contaminants', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('duration', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('duration_type', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('duration_type_methodology', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('format_notes', 'string', null, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => '',
        ));
        $this->hasColumn('type', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('material', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('oxidationcorrosion', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('pack_deformation', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('noise_reduction', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('tape_type', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('thin_tape', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('slow_speed', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('sound_field', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('soft_binder_syndrome', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('gauge', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('color', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('colorfade', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('soundtrackformat', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('substrate', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('strongodor', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('vinegarodor', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('adstriplevel', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('shrinkage', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('levelofshrinkage', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('rust', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('discoloration', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('surfaceblisteringbubbling', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('thintape', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('1993orearlier', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('datagradetape', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('longplay32k96k', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('corrosionrustoxidation', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('composition', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('nonstandardbrand', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('trackconfiguration', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('tapethickness', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('speed', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('softbindersyndrome', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('materialsbreakdown', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('physicaldamage', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('delamination', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('plasticizerexudation', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('recordinglayer', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('recordingspeed', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('cylindertype', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('reflectivelayer', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('datalayer', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('opticaldisctype', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('format', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('recordingstandard', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('publicationyear', 'date', 25, array(
            'type' => 'date',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 25,
        ));
        $this->hasColumn('capacitylayers', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('codec', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('datarate', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('sheddingsoftbinder', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('formatversion', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('oxide', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('bindersystem', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('reelsize', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('whiteresidue', 'integer', 1, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 1,
        ));
        $this->hasColumn('size', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('formattypedvideorecordingformat', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('bitrate', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('scanning', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('format_id', 'integer', 8, array(
            'type' => 'integer',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 8,
        ));
        $this->hasColumn('f_c_name', 'string', 255, array(
            'type' => 'string',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => false,
            'autoincrement' => false,
            'length' => 255,
        ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
            'type' => 'timestamp',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 25,
        ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
            'type' => 'timestamp',
            'fixed' => 0,
            'unsigned' => false,
            'primary' => false,
            'notnull' => true,
            'autoincrement' => false,
            'length' => 25,
        ));
    }

    public function setUp() {
        parent::setUp();
    }

}