<?php

/**
 * BaseStorageLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $env_rating
 * @property Doctrine_Collection $Units
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getEnvRating()  Returns the current record's "env_rating" value
 * @method Doctrine_Collection getUnits()      Returns the current record's "Units" collection
 * @method StorageLocation     setName()       Sets the current record's "name" value
 * @method StorageLocation     setEnvRating()  Sets the current record's "env_rating" value
 * @method StorageLocation     setUnits()      Sets the current record's "Units" collection
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStorageLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('storage_location');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('env_rating', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Unit as Units', array(
             'local' => 'id',
             'foreign' => 'storage_location_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}