<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/15 00:29:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mediaSCORE',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
