<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/10 12:55:00
sfConfig::add(array(
  'app_contactUs' => 'contactus@indiana.edu',
  'app_base' => 'http://mediascore.avpreserve.com',
  'app_url' => 'http://mediascore.avpreserve.com',
));
