<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/12 09:53:34
sfConfig::add(array(
  'app_contactUs' => 'contactus@indiana.edu',
  'app_base' => 'http://mediascore.avpreserve.com',
  'app_url' => 'http://mediascore.avpreserve.com',
));
