<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/28 10:25:19
sfConfig::add(array(
  'app_contactUs' => 'contactus@indiana.edu',
  'app_base' => 'http://mediascore.avpreserve.com',
  'app_url' => 'http://mediascore.avpreserve.com',
));
