<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/28 10:25:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mediascore1_0a',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
