<?php

/**
 * AnalogAudiocassette
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AnalogAudiocassette extends BaseAnalogAudiocassette
{

	/**
	 *
	 * 
	 * @var string[] 
	 */
	public static $constants = array(
		0 => array('' => 'Select', 0 => 'Type I (Normal)', 1 => 'Type II (High Bias: CrO2 or Cobalt Doped)', 2 => 'Type III (Ferric Chrome)',
			3 => 'Type IV (Metal)', 4 => 'Microcassette', 5 => 'Minicassette'),
		1 => array('' => 'Select', 0 => 'Mono', 1 => 'Stereo', 2 => 'Unknown'));

}
