<?php

/**
 * AnalogAudiocassetteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnalogAudiocassetteTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object AnalogAudiocassetteTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('AnalogAudiocassette');
    }

}