<?php

/**
 * AssetGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AssetGroup extends BaseAssetGroup {

    /**
     * calcuate the format duration
     * 
     * @param integer $formatID
     * @return integer 
     */
    public function getDuration($formatID) {
        $totalDuration = 0;

        $formatType = Doctrine_Query::Create()
                ->from('FormatType ft')
                ->select('ft.*')
                ->where('ft.id  = ?', $formatID)
                ->fetchArray();
        if (sizeof($formatType) > 0)
            $totalDuration = $totalDuration + $formatType[0]['duration'];




        return minutesToHour::ConvertMinutes2Hours($totalDuration);
    }
    /**
     * calcuate the format duration
     * 
     * @param integer $formatID
     * @return integer 
     */
    public function getDurationRealTime($formatID) {
        $totalDuration = 0;

        $formatType = Doctrine_Query::Create()
                ->from('FormatType ft')
                ->select('ft.*')
                ->where('ft.id  = ?', $formatID)
                ->fetchArray();
        if (sizeof($formatType) > 0)
            $totalDuration = $totalDuration + $formatType[0]['duration'];




        return minutesToHour::ConvertMinutes2HoursRealTime($totalDuration);
    }

}
