<?php

/**
 * AssetGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetGroupTable extends SubUnitTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetGroup');
    }
}