<?php

/**
 * AudiotapeFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AudiotapeFormatTypeTable extends ReelCassetteFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AudiotapeFormatTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AudiotapeFormatType');
    }
}