<?php

/**
 * Betacam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Betacam extends BaseBetacam
{
	public static $constants = array(0 => array(''=>'Select',0 => 'Small',2 => 'Standard'),
					1 => array(''=>'Select',0 => 'Oxide',1=>'SP'));
}
