<?php

/**
 * BetacamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BetacamTable extends FormatTypedVideoRecordingTable {

    /**
     * Returns an instance of this class.
     *
     * @return object BetacamTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Betacam');
    }

}