<?php

/**
 * BetamaxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BetamaxTable extends VideoRecordingFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object BetamaxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Betamax');
    }
}