<?php

/**
 * CharacteristicsFormatExtendedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CharacteristicsFormatExtendedTable extends FormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CharacteristicsFormatExtendedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CharacteristicsFormatExtended');
    }
}