<?php

/**
 * CharacteristicsConstraintsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CharacteristicsConstraintsTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object CharacteristicsConstraintsTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('CharacteristicsConstraints');
    }

}