<?php

/**
 * CharacteristicsValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CharacteristicsValuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CharacteristicsValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CharacteristicsValues');
    }
}