<?php

/**
 * CharacteristicsFormatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CharacteristicsFormatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CharacteristicsFormatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CharacteristicsFormat');
    }
}