<?php

/**
 * CollectionMultipleAssetGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionMultipleAssetGroupTable extends SubUnitTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollectionMultipleAssetGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CollectionMultipleAssetGroup');
    }
}