<?php

/**
 * CollectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionTable extends SubUnitTable {

    /**
     * Returns an instance of this class.
     *
     * @return object CollectionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Collection');
    }

}