<?php

/**
 * Cylinder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cylinder extends BaseCylinder {

    public static $constants = array('' => 'Select', 0 => 'Cut Wax', 1 => 'Molded Amberol Wax', 2 => 'Other Molded Wax', 3 => 'Molded Celluloid');

}
