<?php

/**
 * CylinderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CylinderTable extends SoftDiskFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CylinderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cylinder');
    }
}