<?php

/**
 * DATTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DATTable extends ReelCassetteFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object DATTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('DAT');
    }

}