<?php

/**
 * DigitalBetacam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DigitalBetacam extends BaseDigitalBetacam
{
	public static $constants = array(
					array(false => 'Small', true => 'Standard'),
					array('Digital','SX','IMX'),
					array('30','40','50'));
}
