<?php

/**
 * DiskFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiskFormatTypeTable extends FormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object DiskFormatTypeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('DiskFormatType');
    }

}