<?php

/**
 * DV
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DV extends BaseDV
{
	public static $constants = array(0 => 'Standard',1 => 'Long Play',2 => 'Unknown');
	public static $constants1 = array(0 => 'Playback Experience',1 => 'Known Problematic Brand');
}
