<?php

/**
 * DVCamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DVCamTable extends SizedVideoRecordingFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object DVCamTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('DVCam');
    }

}