<?php

/**
 * DVCPro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DVCPro extends BaseDVCPro
{
	public static $constants = array(	0 => array(0 => '25', 1 => '50', 2 => 'HD', 3 => 'Unknown'),
						1 => array(0 => 'Standard',1 => 'Long Play',2 => 'Unknown'));
}
