<?php

/**
 * DVCProTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DVCProTable extends FormatVersionedVideoRecordingTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DVCProTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DVCPro');
    }
}