<?php

/**
 * DVTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DVTable extends SizedVideoRecordingFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DVTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DV');
    }
}