<?php

/**
 * EightMMTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EightMMTable extends ReelVideoRecordingFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EightMMTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EightMM');
    }
}