<?php

/**
 * EvaluatorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvaluatorTable extends UserTable {

    /**
     * Returns an instance of this class.
     *
     * @return object EvaluatorTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Evaluator');
    }

}