<?php

/**
 * EvaluatorHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvaluatorHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvaluatorHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EvaluatorHistory');
    }
}