<?php

/**
 * EvaluatorHistoryPersonnelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvaluatorHistoryPersonnelTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object EvaluatorHistoryPersonnelTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('EvaluatorHistoryPersonnel');
    }

}