<?php

/**
 * FilmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilmTable extends ReelCassetteFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FilmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Film');
    }
}