<?php

/**
 * FormatTypedVideoRecordingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormatTypedVideoRecordingTable extends SizedVideoRecordingFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object FormatTypedVideoRecordingTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('FormatTypedVideoRecording');
    }

}