<?php

/**
 * FormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormatTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormatTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormatType');
    }
}