<?php

/**
 * FormatVersionedVideoRecordingTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormatVersionedVideoRecordingTypeTable extends SizedVideoRecordingFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormatVersionedVideoRecordingTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormatVersionedVideoRecordingType');
    }
}