<?php

/**
 * FormatType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FormatType extends BaseFormatType {

    public static $constants = array(0 => 'Original', 1 => 'Copy', 2 => 'Unknown');

    public function getTypeValue() {
        $inheritanceMap = $this->getTable()->getOption('inheritanceMap');
        return isset($inheritanceMap['type']) ? $inheritanceMap['type'] : 0;
    }

    // Key values are for the UI
    // Purposely nested arrays for extension into other character sets
    public static $typeNames = array(
        array('MetalDisc' => 'Metal Disc'),
        array('Film' => 'Film'),
        array('DAT' => 'DAT'),
        array('SoundWireReel' => 'Sound Wire Reel'),
        array('AnalogAudiocassette' => 'Analog Audio Cassette'),
        array('OpenReelAudiotapePolyster' => 'Polyester Open Reel Audio Tape'),
        array('OpenReelAudiotapeAcetate' => 'Acetate Open Reel Audio Tape'),
        array('OpenReelAudiotapePaper' => 'Paper Open Reel Audio Tape'),
        array('OpenReelAudiotapePVC' => 'PVC Open Reel Audio Tape'),
        array('LacquerDisc' => 'Lacquer Disc'),
        array('MiniDisc' => 'MiniDisc'),
        array('Cylinder' => 'Cylinder'),
        array('SoundOpticalDisc' => 'Sound Optical Disc'),
        array('OpticalVideo' => 'Optical Video'),
        array('PressedSeventyEightRPMDisc' => 'Pressed 78RPM Disc'),
        array('PressedLPDisc' => 'Pressed LP Disc'),
        array('PressedFortyFiveRPMDisc' => 'Pressed 45RPM Disc'),
        array('Laserdisc' => 'LaserDisc'),
        array('XDCamOptical' => 'XDCAM Optical'),
        array('Betamax' => 'Betamax'),
        array('EightMM' => '8MM'),
        array('TwoInchOpenReelVideo' => '2" Open Reel Video'),
        array('OneInchOpenReelVideo' => '1" Open Reel Video'),
        array('HalfInchOpenReelVideo' => '½" Open Reel Video'),
        array('DV' => 'DV'),
        array('DVCam' => 'DVCAM'),
        array('Betacam' => 'Betacam'),
        array('VHS' => 'VHS'),
        array('DigitalBetacam' => 'Digital Betacam'),
        array('Umatic' => 'U-matic'),
        array('HDCam' => 'HDCAM'),
        array('DVCPro' => 'DVCPro')
    );
    public static $formatTypesValue = array(
        array('1' => 'Metal Disc'),
        array('5' => 'Film'),
        array('6' => 'DAT'),
        array('7' => 'Sound Wire Reel'),
        array('4' => 'Analog Audio Cassette'),
        array('9' => 'Polyester Open Reel Audio Tape'),
        array('10' => 'Acetate Open Reel Audio Tape'),
        array('11' => 'Paper Open Reel Audio Tape'),
        array('12' => 'PVC Open Reel Audio Tape'),
        array('15' => 'Lacquer Disc'),
        array('16' => 'MiniDisc'),
        array('17' => 'Cylinder'),
        array('19' => 'Sound Optical Disc'),
        array('20' => 'Optical Video'),
        array('22' => 'Pressed 78RPM Disc'),
        array('23' => 'Pressed LP Disc'),
        array('24' => 'Pressed 45RPM Disc'),
        array('26' => 'LaserDisc'),
        array('27' => 'XDCAM Optical'),
        array('29' => 'Betamax'),
        array('31' => '8MM'),
        array('33' => '2" Open Reel Video'),
        array('34' => '1" Open Reel Video'),
        array('35' => '½" Open Reel Video'),
        array('37' => 'DV'),
        array('38' => 'DVCAM'),
        array('40' => 'Betacam'),
        array('41' => 'VHS'),
        array('42' => 'Digital Betacam'),
        array('44' => 'U-matic'),
        array('45' => 'HDCAM'),
        array('46' => 'DVCPro')
    );
    public static $formatTypesValue1d = array(
        '1' => 'Metal Disc',
        '5' => 'Film',
        '6' => 'DAT',
        '7' => 'Sound Wire Reel',
        '4' => 'Analog Audio Cassette',
        '9' => 'Polyester Open Reel Audio Tape',
        '10' => 'Acetate Open Reel Audio Tape',
        '11' => 'Paper Open Reel Audio Tape',
        '12' => 'PVC Open Reel Audio Tape',
        '15' => 'Lacquer Disc',
        '16' => 'MiniDisc',
        '17' => 'Cylinder',
        '19' => 'Sound Optical Disc',
        '20' => 'Optical Video',
        '22' => 'Pressed 78RPM Disc',
        '23' => 'Pressed LP Disc',
        '24' => 'Pressed 45RPM Disc',
        '26' => 'LaserDisc',
        '27' => 'XDCAM Optical',
        '29' => 'Betamax',
        '31' => '8MM',
        '33' => '2" Open Reel Video',
        '34' => '1" Open Reel Video',
        '35' => '½" Open Reel Video',
        '37' => 'DV',
        '38' => 'DVCAM',
        '40' => 'Betacam',
        '41' => 'VHS',
        '42' => 'Digital Betacam',
        '44' => 'U-matic',
        '45' => 'HDCAM',
        '46' => 'DVCPro'
    );

    static function getFormatTypesValue() {
        return $this->formatTypesValue;
    }

}
