<?php

/**
 * HalfInchOpenReelVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HalfInchOpenReelVideoTable extends OpenReelVideoFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object HalfInchOpenReelVideoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('HalfInchOpenReelVideo');
    }

}