<?php

/**
 * HalfInchOpenReelVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HalfInchOpenReelVideo extends BaseHalfInchOpenReelVideo {

    public static $constants = array(
        0 => array('' => 'Select', 0 => 'EIAJ', 1 => 'CV', 2 => 'Unknown'),
        1 => array(0 => '3"', 1 => '5"'));

}
