<?php

/**
 * HDCamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HDCamTable extends FormatVersionedVideoRecordingTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object HDCamTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('HDCam');
    }

}