<?php

/**
 * HDCam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HDCam extends BaseHDCam {

    public static $constants = array(0 => array('' => 'Select', 0 => 'Standard', 1 => 'SR'),
        1 => array(0 => 'HQ',
            1 => 'SQ',
            2 => 'SR Lite',
            3 => 'Unknown'),
        2 => array('' => 'Select', 0 => 'Interlaced',
            1 => 'Progressive',
            2 => 'Unknown'));

}
