<?php

/**
 * Laserdisc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Laserdisc extends BaseLaserdisc
{
	public static $constants = array(0 => 'Standard',1 => 'Extended',2 => 'Unknown');
}
