<?php

/**
 * LaserdiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LaserdiscTable extends StandardizedRecordingFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object LaserdiscTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Laserdisc');
    }

}