<?php

/**
 * MetalDiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetalDiscTable extends FormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object MetalDiscTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('MetalDisc');
    }

}