<?php

/**
 * MetalDisc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MetalDisc extends BaseMetalDisc {

    public static $constants = array('' => 'Select', '0' => 'Aluminum', '1' => 'Pregrooved Zinc', '2' => 'Unknown');
    public static $generation = array('' => 'Select', '0' => 'Original', '1' => 'Copy', '2' => 'Unknown');
    public static $damage = array('0' => 'None', '1' => 'Minor', '2' => 'Moderate', '3' => 'Severe');

}

