<?php

/**
 * MiniDiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiniDiscTable extends SoftDiskFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object MiniDiscTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('MiniDisc');
    }

}