<?php

/**
 * MiniDisc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MiniDisc extends BaseMiniDisc
{
	public static $constants = array(0 => array(0 => 'Recordable',1 => 'Molded (Pre-Recorded)'),
					1 => array(0 => 'SP',1 => 'LP2',2 => 'LP4'));
}
