<?php

/**
 * OneInchOpenReelVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OneInchOpenReelVideoTable extends OpenReelVideoFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OneInchOpenReelVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OneInchOpenReelVideo');
    }
}