<?php

/**
 * OneInchOpenReelVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OneInchOpenReelVideo extends BaseOneInchOpenReelVideo
{

	public static $constants = array(
		0 => array( 0 => 'Type A', 1 => 'Type B', 2 => 'Type C', 3 => 'IVC', 4 => 'Unknown'),
		1 =>
		array(0 => 'Spot, 9"',
			1 => '10.5"',
			2 => '11.75"',
			3 => '14"',
			4 => '8"',
			5 => '12.5"',
			6 => '7"'));

}
