<?php

/**
 * OpenReelAudioTapeFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenReelAudioTapeFormatTypeTable extends AudiotapeFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpenReelAudioTapeFormatTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpenReelAudioTapeFormatType');
    }
}