<?php

/**
 * OpenReelAudiotapePolysterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenReelAudiotapePolysterTable extends OpenReelAudioTapeFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object OpenReelAudiotapePolysterTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('OpenReelAudiotapePolyster');
    }

}