<?php

/**
 * OpenReelAudiotapePVCTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenReelAudiotapePVCTable extends OpenReelAudioTapeFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object OpenReelAudiotapePVCTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('OpenReelAudiotapePVC');
    }

}