<?php

/**
 * OpenReelAudiotapeAcetateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenReelAudiotapeAcetateTable extends OpenReelAudioTapeFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object OpenReelAudiotapeAcetateTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('OpenReelAudiotapeAcetate');
    }

}