<?php

/**
 * OpenReelAudiotapePaperTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenReelAudiotapePaperTable extends OpenReelAudioTapeFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpenReelAudiotapePaperTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpenReelAudiotapePaper');
    }
}