<?php

/**
 * OpenReelAudioTapeFormatType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OpenReelAudioTapeFormatType extends BaseOpenReelAudioTapeFormatType
{
	public static $constants = array(
					0 => array(0 => 'Full Track',1 => 'Mono',2 => 'Half-Track Mono',3 => 'Half-Track Stereo',4 => 'Quarter-Track Mono',5 => 'Quarter-Track Stereo',6 => 'Unknown'),
					1 => array(0 => 'Problem Brand A',1 => 'Problem Brand B'));
}
