<?php

/**
 * OpenReelAudiotapePolyster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OpenReelAudiotapePolyster extends BaseOpenReelAudiotapePolyster {

    public static $constants = array(
        0 => array(0 => 'Standard Play', 1 => 'Long Play', 2 => 'Double Play', 3 => 'Triple Play', 4 => 'Unknown'),
        1 => array(0 => '0.9375 ips', 1 => '1.875 ips', 2 => '3.75 ips', 3 => '7.5 ips', 4 => '15 ips', 5 => '30 ips', 6 => 'Unknown'));

}
