<?php

/**
 * OpenReelAudioTapeFormatType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OpenReelAudioTapeFormatType extends BaseOpenReelAudioTapeFormatType {

    public static $constants = array(
        0 => array('' => 'Select', 0 => 'Full Track', 1 => 'Mono', 2 => 'Half-Track Mono', 3 => 'Half-Track Stereo', 4 => 'Quarter-Track Mono', 5 => 'Quarter-Track Stereo', 6 => 'Unknown'),
        1 => array(0 => 'Problem Brand A', 1 => 'Problem Brand B', 2 => 'Playback experience'),
        2 => array(0 => '0.9375 ips', 1 => '1.875 ips', 2 => '3.75 ips', 3 => '7.5 ips', 4 => '15 ips', 5 => '30 ips', 6 => 'unknown'),
        3 => array('' => 'Select', 0 => 'Standard Play', 1 => 'Long Play', 2 => 'Double Play', 3 => 'Triple Play', 4 => 'Unknown'));

}
