<?php

/**
 * OpenReelVideoFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpenReelVideoFormatTypeTable extends ReelVideoRecordingFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpenReelVideoFormatTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpenReelVideoFormatType');
    }
}