<?php

/**
 * OpticalVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpticalVideoTable extends OpticalDiscFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpticalVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OpticalVideo');
    }
}