<?php

/**
 * OpticalVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OpticalVideo extends BaseOpticalVideo
{
	public static $constants = array(
					0 => array(''=>'Select',0 => 'Data',1 => 'Video',2 => 'Unknown'),
					1 => array(''=>'Select',0 => 'DVD',1 => 'DVD±',2 => 'VCD',3 => 'CD ±R'));
}
