<?php

/**
 * PersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonTable extends UserTable {

    /**
     * Returns an instance of this class.
     *
     * @return object PersonTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Person');
    }

}
