<?php

/**
 * PressedFortyFiveRPMDiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressedFortyFiveRPMDiscTable extends PressedAudioDiscFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object PressedFortyFiveRPMDiscTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PressedFortyFiveRPMDisc');
    }

}