<?php

/**
 * PressedLPDiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressedLPDiscTable extends PressedAudioDiscFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object PressedLPDiscTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PressedLPDisc');
    }

}