<?php

/**
 * Pressed45RPMDiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Pressed45RPMDiscTable extends PressedAudioDiscFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Pressed45RPMDiscTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pressed45RPMDisc');
    }
}