<?php

/**
 * Pressed78RPMDiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Pressed78RPMDiscTable extends PressedAudioDiscFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object Pressed78RPMDiscTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Pressed78RPMDisc');
    }

}