<?php

/**
 * PressedSeventyEightRPMDiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressedSeventyEightRPMDiscTable extends PressedAudioDiscFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object PressedSeventyEightRPMDiscTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PressedSeventyEightRPMDisc');
    }

}