<?php

/**
 * PressedAudioDiscFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressedAudioDiscFormatTypeTable extends SoftDiskFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object PressedAudioDiscFormatTypeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('PressedAudioDiscFormatType');
    }

}