<?php

/**
 * ReelCassetteFormatType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ReelCassetteFormatType extends BaseReelCassetteFormatType
{
	public static $constants = array(0=>'None',1 => 'Minor',2 => 'Moderate',3 => 'Severe'); 
}
