<?php

/**
 * ReelCassetteFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReelCassetteFormatTypeTable extends FormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReelCassetteFormatTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReelCassetteFormatType');
    }
}