<?php

/**
 * ReelVideoRecordingFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReelVideoRecordingFormatTypeTable extends VideoRecordingFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object ReelVideoRecordingFormatTypeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ReelVideoRecordingFormatType');
    }

}