<?php

/**
 * ReportsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reports');
    }
}