<?php

/**
 * SimpleSubUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SimpleSubUnitTable extends UnitTable {

    /**
     * Returns an instance of this class.
     *
     * @return object SimpleSubUnitTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('SimpleSubUnit');
    }

}