<?php

/**
 * SizedVideoRecordingFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SizedVideoRecordingFormatTypeTable extends VideoRecordingFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object SizedVideoRecordingFormatTypeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('SizedVideoRecordingFormatType');
    }

}