<?php

/**
 * SoftDiskFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SoftDiskFormatTypeTable extends DiskFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SoftDiskFormatTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SoftDiskFormatType');
    }
}