<?php

/**
 * SoundWireReelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SoundWireReelTable extends ReelCassetteFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SoundWireReelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SoundWireReel');
    }
}