<?php

/**
 * SoundOpticalDiscTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SoundOpticalDiscTable extends OpticalDiscFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SoundOpticalDiscTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SoundOpticalDisc');
    }
}