<?php

/**
 * SoundOpticalDiskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SoundOpticalDiskTable extends OpticalDiscFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object SoundOpticalDiskTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('SoundOpticalDisk');
    }

}