<?php

/**
 * StandardizedRecordingFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StandardizedRecordingFormatTypeTable extends DiskFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object StandardizedRecordingFormatTypeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('StandardizedRecordingFormatType');
    }

}