<?php

/**
 * StandardizedRecordingFormatType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StandardizedRecordingFormatType extends BaseStandardizedRecordingFormatType
{
	public static $constants = array(0 => 'NTSC',1 => 'PAL',2 => 'SECAM',3 => 'Unknown');
}
