<?php

/**
 * StoreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoreTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object StoreTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Store');
    }

}