<?php

/**
 * StorageLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StorageLocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StorageLocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StorageLocation');
    }
}