<?php

/**
 * SubUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubUnitTable extends StoreTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubUnit');
    }
}