<?php

/**
 * TwoInchOpenReelVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TwoInchOpenReelVideoTable extends OpenReelVideoFormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TwoInchOpenReelVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TwoInchOpenReelVideo');
    }
}