<?php

/**
 * TwoInchOpenReelVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TwoInchOpenReelVideo extends BaseTwoInchOpenReelVideo
{
	public static $constants = array(0 => array(0 => 'Quad',1 => 'IVC', 2 => 'Unknown'),
					1 =>
						array(0 => 'Spot',
							1 => 'Cartridge',
							2 => '10.5"',
							3 => '14"'));
}
