<?php

/**
 * Umatic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Nouman Tayyab
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Umatic extends BaseUmatic {

    public static $constants = array(0 => array('' => 'Select', 0 => 'Small', 1 => 'Standard'),
        1 => array('' => 'Select',
            0 => 'Low Band',
            1 => 'High Band',
            2 => 'SP',
            3 => 'Unknown'));

}
