<?php

/**
 * UmaticTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UmaticTable extends FormatVersionedVideoRecordingTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UmaticTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Umatic');
    }
}