<?php

/**
 * UnitStorageLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitStorageLocationTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UnitStorageLocationTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('UnitStorageLocation');
    }

}