<?php

/**
 * UnitPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitPersonTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UnitPersonTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('UnitPerson');
    }

}