<?php

/**
 * UnitMultipleCollectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitMultipleCollectionTable extends StoreTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitMultipleCollectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnitMultipleCollection');
    }
}