<?php

/**
 * UnitPersonUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitPersonUserTable extends UnitPersonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitPersonUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnitPersonUser');
    }
}