<?php

/**
 * UnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Unit');
    }
}