<?php

/**
 * VHS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mediaSCORE
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VHS extends BaseVHS
{
	public static $constants = array(0 => array(false => 'Small',true => 'Standard'),
					1 => array(0 => 'VHS', 1=>'SVHS'),
					2 =>
						array(0 => 'Standard',
						1 => 'Long Play',
						2 => 'Extended or Super Long Play',
						3 => 'Unknown'));
}
