<?php

/**
 * VHSTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VHSTable extends FormatTypedVideoRecordingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VHSTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VHS');
    }
}