<?php

/**
 * VideoRecordingFormatTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoRecordingFormatTypeTable extends FormatTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoRecordingFormatTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VideoRecordingFormatType');
    }
}