<?php

/**
 * XDCamOpticalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class XDCamOpticalTable extends StandardizedRecordingFormatTypeTable {

    /**
     * Returns an instance of this class.
     *
     * @return object XDCamOpticalTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('XDCamOptical');
    }

}