production:
    .settings:
        base:       http://mediascore.avpreserve.com
        url: http://mediascore.avpreserve.com
        
qa:
    .settings:
        base:     http://mediascoreqa.avpreserve.com
        url: http://mediascoreqa.avpreserve.com
testing:
    .settings:
        base:     http://mediascore.live.geekschicago.com/frontend_dev.php
        url: http://mediascore.live.geekschicago.com/index.php
 
local:
    .settings:
        base:     http://avp.localhost/frontend_dev.php
        url: http://avp.localhost
        base_path : checking/
        
all:
  .settings:
      contactUs:     contactus@indiana.edu
      