# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
prod:
    .settings:
        base:       http://mediascore.avpreserve.com
        
dev:
    .settings:
        base:     http://108.166.74.254/frontend_dev.php

        
        
all:
  .settings:
      contactUs:     contactus@indiana.edu
      