all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      #dsn: mysql:host=localhost;dbname=indiana
      #username: indiana 
      #password: pl@123
      #dsn: mysql:host=localhost;dbname=mediascore
      #username: root
      #password: 
      dsn: mysql:host=localhost;dbname=mediaSCORE1_0a
      username: symfony
      password: sYmF0nYd3v




