all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      #dsn: mysql:host=localhost;dbname=indiana
      #username: indiana 
      #password: pl@123
      dsn: mysql:host=localhost;dbname=mediascore
      username: symfony
      password: sYmF0nYd3v
