production:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascore_live
      username: mediascore_live
      password: mediascore_live#456
qa:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediaSCORE1_0a
      username: symfony
      password: sYmF0nYd3v
testing:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascore
      username: mediascore
      password: xoho@123
local:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascore
      username: root
      password: 

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascore_live
      username: mediascore_live
      password: mediascore_live#456




