production:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascorepro
      username: mediascorepro
      password: avps@123
qa:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascore
      username: mediascore
      password: avps@123
testing:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascore
      username: mediascore
      password: xoho@123
local:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascore
      username: root
      password: 

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: mysql:host=localhost;dbname=mediascorepro
      username: mediascorepro
      password: avps@123




