<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/15 12:47:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mediaSCORE1_0a',
  'username' => 'symfony',
  'password' => 'sYmF0nYd3v',
  'name' => 'doctrine',
)),);
