<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 19:50:10
sfConfig::add(array(
  'mod_halfinchopenreelvideo_enabled' => true,
  'mod_halfinchopenreelvideo_view_class' => 'sfPHP',
));
