<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 19:54:11
sfConfig::add(array(
  'mod_twoinchopenreelvideo_enabled' => true,
  'mod_twoinchopenreelvideo_view_class' => 'sfPHP',
));
