<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 20:35:34
sfConfig::add(array(
  'mod_openreelaudiotapeacetate_enabled' => true,
  'mod_openreelaudiotapeacetate_view_class' => 'sfPHP',
));
