<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 23:01:21
sfConfig::add(array(
  'mod_openreelaudiotapepvc_enabled' => true,
  'mod_openreelaudiotapepvc_view_class' => 'sfPHP',
));
