<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/21 19:32:54
sfConfig::add(array(
  'mod_audiotapeformattype_enabled' => true,
  'mod_audiotapeformattype_view_class' => 'sfPHP',
));
