<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/15 15:30:16
sfConfig::add(array(
  'mod_evaluatorhistory_enabled' => true,
  'mod_evaluatorhistory_view_class' => 'sfPHP',
));
