<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/21 22:56:08
sfConfig::add(array(
  'mod_analogaudiocassette_enabled' => true,
  'mod_analogaudiocassette_view_class' => 'sfPHP',
));
