<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 19:52:20
sfConfig::add(array(
  'mod_oneinchopenreelvideo_enabled' => true,
  'mod_oneinchopenreelvideo_view_class' => 'sfPHP',
));
