<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 23:00:59
sfConfig::add(array(
  'mod_openreelaudiotapepolyster_enabled' => true,
  'mod_openreelaudiotapepolyster_view_class' => 'sfPHP',
));
