<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 18:52:31
sfConfig::add(array(
  'mod_digitalbetacam_enabled' => true,
  'mod_digitalbetacam_view_class' => 'sfPHP',
));
