<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 23:01:17
sfConfig::add(array(
  'mod_openreelaudiotapepaper_enabled' => true,
  'mod_openreelaudiotapepaper_view_class' => 'sfPHP',
));
