<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/22 20:21:11
sfConfig::add(array(
  'mod_soundopticaldisk_enabled' => true,
  'mod_soundopticaldisk_view_class' => 'sfPHP',
));
